apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-delete
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - delete
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - pods/eviction
    verbs:
      - create
