---
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver-vip
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: kube-apiserver-vip
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
    - name: kube-keepalived-vip
      image: ${keepalived_vip_image}
      imagePullPolicy: Always
      args:
        - "--run-only"
        - process
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /dev
          name: dev
        - mountPath: /usr/local/etc/keepalived/keepalived.conf
          name: config-keepalived-conf
          readOnly: true
        - mountPath: /apiserver-vip
          name: config
          readOnly: true
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
    - name: kube-keepalived-vip-liveness
      image: ${kubelet_image}
      imagePullPolicy: Always
      command:
        - "/bin/sleep"
      args:
        - "365d"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBECONFIG
          value: "/etc/kubernetes/kubeconfig"
      livenessProbe:
        exec:
          command:
            - "kubectl"
            - "get"
            - "--raw"
            - "/healthz"
        initialDelaySeconds: 20
        periodSeconds: 5
        failureThreshold: 2
        successThreshold: 1
  volumes:
    - name: modules
      hostPath:
        path: /lib/modules
    - name: dev
      hostPath:
        path: /dev
    - name: config
      hostPath:
        path: /etc/kubernetes/extra-assets/apiserver-vip
        type: Directory
    - name: config-keepalived-conf
      hostPath:
        path: /etc/kubernetes/extra-assets/apiserver-vip/keepalived.conf
        type: File
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/bootstrap-secrets/kubeconfig-localhost
        type: File
