---
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver-vip
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: kube-apiserver-vip
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
    - name: keepalived
      image: ${keepalived_vip_image}
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /dev
          name: dev
        - mountPath: /etc/keepalived/keepalived.conf
          name: config-keepalived-conf
          readOnly: true
        - mountPath: /apiserver-vip
          name: config
          readOnly: true
        - mountPath: /run
          name: run
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
    - name: check-apiserver
      image: ${kubelet_image}
      imagePullPolicy: Always
      command:
        - "/apiserver-vip/check-apiserver-health.sh"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /apiserver-vip
          name: config
          readOnly: true
        - mountPath: /run
          name: run
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBECONFIG
          value: "/etc/kubernetes/kubeconfig"
  volumes:
    - name: modules
      hostPath:
        path: /lib/modules
    - name: dev
      hostPath:
        path: /dev
    - name: config
      hostPath:
        path: /etc/kubernetes/extra-assets/apiserver-vip
        type: Directory
    - name: config-keepalived-conf
      hostPath:
        path: /etc/kubernetes/extra-assets/apiserver-vip/keepalived.conf
        type: File
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/pki/kubeconfig-localhost
        type: File
    - name: run
      emptyDir: {}
